export default [
  {
    index: 0,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'sid1AB-NQ0K_qqM-0P_UF',
  },
  {
    index: 1,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'CxZW2EsWn3iJszgbg8SsP',
  },
  {
    index: 2,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'sDqR9XmG2042woSrRVx45',
  },
  {
    index: 3,
    isBomb: false,
    value: 0,
    clicked: false,
    key: '6V6Ff8Sq8lDpzriqwznfC',
  },
  {
    index: 4,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'l6eqZ7Zfr6jCXpVldJVEN',
  },
  {
    index: 5,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'S0ItJyM4lV3Kw3KOi1eOP',
  },
  {
    index: 6,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'uVl8MM6o5CPbup4PChtpl',
  },
  {
    index: 7,
    isBomb: true,
    value: 0,
    clicked: false,
    key: 'FucqkTT8FkoqSAMZlEeiQ',
  },
  {
    index: 8,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'GxP4ln7BBhOmbJvTAaqrP',
  },
  {
    index: 9,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'YRyIid596eg09muCDp3J0',
  },
  {
    index: 10,
    isBomb: false,
    value: 0,
    clicked: false,
    key: '_PQhxjuP7za47qzdXeZD1',
  },
  {
    index: 11,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'dshu6rZInzgAqaSk6TL3z',
  },
  {
    index: 12,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'bDOzCElSa_ids-xZjzO4f',
  },
  {
    index: 13,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'j9nS_0cuNMsmSmE79wK9G',
  },
  {
    index: 14,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'zHavCz6MMFTpitcXzWcrS',
  },
  {
    index: 15,
    isBomb: false,
    value: 0,
    clicked: false,
    key: '6xtFiEi0leHGCVZofUCj_',
  },
  {
    index: 16,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'PqgoKhJT1Rg6_ZbwjZl2z',
  },
  {
    index: 17,
    isBomb: false,
    value: 0,
    clicked: false,
    key: '3sho_MgvEE4UBJJfYVxKX',
  },
  {
    index: 18,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'IEjCS4Cev7OG0eYTzALeW',
  },
  {
    index: 19,
    isBomb: false,
    value: 0,
    clicked: false,
    key: '71EXNjsFRWn6ehUAjXSSZ',
  },
  {
    index: 20,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'HZGzTYSHatD_UjiKH3oC1',
  },
  {
    index: 21,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'FE2wI5ptjwwkeU1p2wNSS',
  },
  {
    index: 22,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'ixO66uaJv38dGgSPggv8U',
  },
  {
    index: 23,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'cleY2B3ddGocREbVK8v1R',
  },
  {
    index: 24,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'i-XezgMWBoCnYDDFdqDUm',
  },
  {
    index: 25,
    isBomb: true,
    value: 0,
    clicked: false,
    key: 'vhUM7Jgz3bl6W5whSNC25',
  },
  {
    index: 26,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'CoG53DByPSStCSmarbA73',
  },
  {
    index: 27,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'NwWPcgKjE_nNCb5JIR1VE',
  },
  {
    index: 28,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'wPEDlfvuN4KqqleAKepYO',
  },
  {
    index: 29,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'CyUa-uNdAPY5fOodq2T0w',
  },
  {
    index: 30,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'OH9WDk0-G3ThOpXVl4SP6',
  },
  {
    index: 31,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'gJmhbKZ90EFMksXP4yQmn',
  },
  {
    index: 32,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'ZnHIMwSm4fZRlyUnukKLx',
  },
  {
    index: 33,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'y9YaKTsAiwI_DNs0C1zsU',
  },
  {
    index: 34,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'Iz351hsTwJt5KfEKx0587',
  },
  {
    index: 35,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'LkpP-4XVyWjCo7lAd5RZh',
  },
  {
    index: 36,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'MXGIWeiFIqGu3HrBXswQp',
  },
  {
    index: 37,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'QIJrbbeFFDkqyOzokb2CL',
  },
  {
    index: 38,
    isBomb: false,
    value: 0,
    clicked: false,
    key: '2uUVi-oELJ1Mi5uG2RO9j',
  },
  {
    index: 39,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'Z_4f8dERu1ye1abAOVpUL',
  },
  {
    index: 40,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'LGjTQ_90KiscSU5q6oXac',
  },
  {
    index: 41,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 't7r8z6zLyg0cj68gkF39G',
  },
  {
    index: 42,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'gMy7aXGkiWwBJVkK2Pwy_',
  },
  {
    index: 43,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'paobwnIlAfNuyeq_sqTNZ',
  },
  {
    index: 44,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'b14PR7u2eDHnNpfMgzrZG',
  },
  {
    index: 45,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'TBsP8DM0UHzQsTdy3Q1tN',
  },
  {
    index: 46,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'PGFrrX_vFd1P5N71V7EE_',
  },
  {
    index: 47,
    isBomb: false,
    value: 0,
    clicked: false,
    key: '_1ihAWjP9aNuCkBDTkLeq',
  },
  {
    index: 48,
    isBomb: false,
    value: 0,
    clicked: false,
    key: 'lUAktk0uKR1fZF9zYbyO8',
  },
];
